"""add vector index metadata

Revision ID: 10ef3ebc0e8f
Revises: c26de5afcab2
Create Date: 2026-08-17 21:38:32.661078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ef3ebc0e8f'
down_revision: Union[str, Sequence[str], None] = 'c26de5afcab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_versions', sa.Column('vector_indexed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('paper_versions', sa.Column('vector_count', sa.Integer(), nullable=True))
    op.add_column('paper_versions', sa.Column('embedding_provider', sa.String(length=64), nullable=True))
    op.add_column('paper_versions', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('paper_versions', sa.Column('embedding_config_fingerprint', sa.String(length=128), nullable=True))
    op.add_column('paper_versions', sa.Column('vector_generation_fingerprint', sa.String(length=128), nullable=True))
    op.add_column('paper_versions', sa.Column('qdrant_collection', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_versions', 'qdrant_collection')
    op.drop_column('paper_versions', 'vector_generation_fingerprint')
    op.drop_column('paper_versions', 'embedding_config_fingerprint')
    op.drop_column('paper_versions', 'embedding_model')
    op.drop_column('paper_versions', 'embedding_provider')
    op.drop_column('paper_versions', 'vector_count')
    op.drop_column('paper_versions', 'vector_indexed_at')
    # ### end Alembic commands ###
