"""add paper version artifact metadata

Revision ID: 4998b821124e
Revises: eaad6856b1de
Create Date: 2026-08-17 17:37:31.337258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4998b821124e'
down_revision: Union[str, Sequence[str], None] = 'eaad6856b1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_versions', sa.Column('storage_path', sa.String(length=2048), nullable=True))
    op.add_column('paper_versions', sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('paper_versions', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_versions', 'file_size_bytes')
    op.drop_column('paper_versions', 'downloaded_at')
    op.drop_column('paper_versions', 'storage_path')
    # ### end Alembic commands ###
