"""add chunk config fingerprint

Revision ID: c26de5afcab2
Revises: 7a23a77df74a
Create Date: 2026-08-17 20:56:51.454945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26de5afcab2'
down_revision: Union[str, Sequence[str], None] = '7a23a77df74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_versions', sa.Column('chunk_config_fingerprint', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_versions', 'chunk_config_fingerprint')
    # ### end Alembic commands ###
