"""add graph extraction metadata

Revision ID: d002a4409dd0
Revises: 10ef3ebc0e8f
Create Date: 2026-08-18 15:10:46.537981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd002a4409dd0'
down_revision: Union[str, Sequence[str], None] = '10ef3ebc0e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_versions', sa.Column('graph_extraction_artifact_path', sa.String(length=2048), nullable=True))
    op.add_column('paper_versions', sa.Column('graph_extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('paper_versions', sa.Column('entity_count', sa.Integer(), nullable=True))
    op.add_column('paper_versions', sa.Column('relationship_count', sa.Integer(), nullable=True))
    op.add_column('paper_versions', sa.Column('extraction_version', sa.String(length=32), nullable=True))
    op.add_column('paper_versions', sa.Column('extraction_config_fingerprint', sa.String(length=128), nullable=True))
    op.add_column('paper_versions', sa.Column('graph_extraction_generation_fingerprint', sa.String(length=128), nullable=True))
    op.add_column('paper_versions', sa.Column('graph_extraction_artifact_checksum', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_versions', 'graph_extraction_artifact_checksum')
    op.drop_column('paper_versions', 'graph_extraction_generation_fingerprint')
    op.drop_column('paper_versions', 'extraction_config_fingerprint')
    op.drop_column('paper_versions', 'extraction_version')
    op.drop_column('paper_versions', 'relationship_count')
    op.drop_column('paper_versions', 'entity_count')
    op.drop_column('paper_versions', 'graph_extracted_at')
    op.drop_column('paper_versions', 'graph_extraction_artifact_path')
    # ### end Alembic commands ###
