"""initial control plane

Revision ID: eaad6856b1de
Revises: 
Create Date: 2026-08-17 16:52:38.941016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaad6856b1de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('paper_id', name=op.f('pk_papers')),
    sa.UniqueConstraint('source', 'source_id', name='uq_papers_source_source_id')
    )
    op.create_table('paper_versions',
    sa.Column('paper_version_id', sa.String(length=255), nullable=False),
    sa.Column('paper_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_paper_versions_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_version_id', name=op.f('pk_paper_versions')),
    sa.UniqueConstraint('paper_id', 'version', name='uq_paper_versions_paper_id_version')
    )
    op.create_table('ingestion_jobs',
    sa.Column('ingestion_job_id', sa.String(length=255), nullable=False),
    sa.Column('paper_id', sa.String(length=255), nullable=False),
    sa.Column('paper_version_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failed_stage', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_ingestion_jobs_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], name=op.f('fk_ingestion_jobs_paper_version_id_paper_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingestion_job_id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index('ix_ingestion_jobs_paper_version_status', 'ingestion_jobs', ['paper_version_id', 'status'], unique=False)
    op.create_index('uq_ingestion_jobs_one_active_per_version', 'ingestion_jobs', ['paper_version_id'], unique=True, postgresql_where=sa.text("status NOT IN ('ready', 'failed')"))
    op.create_table('ingestion_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_job_id', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.ingestion_job_id'], name=op.f('fk_ingestion_steps_ingestion_job_id_ingestion_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_ingestion_steps')),
    sa.UniqueConstraint('ingestion_job_id', 'stage', 'attempt', name='uq_ingestion_steps_job_stage_attempt')
    )
    op.create_index('ix_ingestion_steps_job_stage', 'ingestion_steps', ['ingestion_job_id', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_steps_job_stage', table_name='ingestion_steps')
    op.drop_table('ingestion_steps')
    op.drop_index('uq_ingestion_jobs_one_active_per_version', table_name='ingestion_jobs', postgresql_where=sa.text("status NOT IN ('ready', 'failed')"))
    op.drop_index('ix_ingestion_jobs_paper_version_status', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('paper_versions')
    op.drop_table('papers')
    # ### end Alembic commands ###
